version: "3"

services:
  # consul server, expose ui port 8500, the cluster would work only the servers number more than 2
  consulserver:
    image: progrium/consul:latest
    hostname: consulserver
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
      - "53"
    command: -server -ui-dir /ui -data-dir /tmp/consul --bootstrap-expect=2
    networks:
      - kong-net

  # consul server1 join the consul server after the consulserver worked
  consulserver1:
    image: progrium/consul:latest
    hostname: consulserver1
    depends_on:
      - "consulserver"
    ports:
      - "8300"
      - "8400"
      - "8500"
      - "8600"
      - "8600/udp"
      - "53"
    command: -server -data-dir /tmp/consul -join consulserver
    networks:
      - kong-net
  # consul server2 join the consul server after the consulserver workedß
  consulserver2:
    image: progrium/consul:latest
    hostname: consulserver2
    depends_on:
      - "consulserver"
    ports:
      - "8300"
      - "8400"
      - "8500"
      - "8600"
      - "8600/udp"
      - "53"
    command: -server -data-dir /tmp/consul -join consulserver
    networks:
      - kong-net
  # listen the new port in the container
  registrator:
    image: gliderlabs/registrator:master
    hostname: registrator
    depends_on:
      - "consulserver"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -internal consul://consulserver:8500
    networks:
      - kong-net
  serviceweb:
    image: fasimito/node-microservice-web
    depends_on:
      - "consulserver"
    environment:
      SERVICE_3000_NAME: microserviceweb
    ports:
      - "3000"
    networks:
      - kong-net

  kong-database:
    image: postgres:11
    networks:
      - kong-net
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true

  kong:
    image: kong:latest
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    networks:
      - kong-net
    depends_on:
      - kong-database
      - consulserver
    command: >
      sh -c "kong migrations up && kong migrations bootstrap && sh /docker-entrypoint.sh kong docker-start"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=${KONG_PG_HOST:-kong-database}
      - KONG_PG_USER=${KONG_PG_USER:-kong}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD:-kong}
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL= 0.0.0.0:8444
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
    restart: on-failure

  kong-dashboard:
    image: pgbi/kong-dashboard:v2
    ports:
      - "8080:8080"
    networks:
      - kong-net
    depends_on:
      - kong
networks:
  kong-net:
