version: "3"

services:
  dnsmasq:
    image: andyshinn/dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    hostname: dns-server
    command: --log-facility=-
    volumes:
      - ./data/dnsmasq.conf:/etc/dnsmasq.conf
      - ./data/dnsmasq.d:/etc/dnsmasq.d